[package]
name = "simple"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
mcp-agent = {path = "../../mcp-agent"}
rmcp.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
